// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp1LZnNlxD8Kp5HprgJ7Ch-7lnsGoDHRE',
    appId: '1:292212591013:web:a85dbad5f3b5d6871fc04c',
    messagingSenderId: '292212591013',
    projectId: 'project-1662196727563872745',
    authDomain: 'project-1662196727563872745.firebaseapp.com',
    storageBucket: 'project-1662196727563872745.appspot.com',
    measurementId: 'G-R25CRWX3P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhMKQfzNDsTkeCbIbELjXxz5H-2Qbv2Qk',
    appId: '1:292212591013:android:bd57436f98a6857b1fc04c',
    messagingSenderId: '292212591013',
    projectId: 'project-1662196727563872745',
    storageBucket: 'project-1662196727563872745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjv4PELj4aNtYFgPRSRpd-6oH0T0X9fhk',
    appId: '1:292212591013:ios:3b7509d4369b5ef81fc04c',
    messagingSenderId: '292212591013',
    projectId: 'project-1662196727563872745',
    storageBucket: 'project-1662196727563872745.appspot.com',
    iosClientId: '292212591013-jptgasdarjcpq4n70srbm0ibgvpra7vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjv4PELj4aNtYFgPRSRpd-6oH0T0X9fhk',
    appId: '1:292212591013:ios:3b7509d4369b5ef81fc04c',
    messagingSenderId: '292212591013',
    projectId: 'project-1662196727563872745',
    storageBucket: 'project-1662196727563872745.appspot.com',
    iosClientId: '292212591013-jptgasdarjcpq4n70srbm0ibgvpra7vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp1LZnNlxD8Kp5HprgJ7Ch-7lnsGoDHRE',
    appId: '1:292212591013:web:29f0c4e5abacf6bf1fc04c',
    messagingSenderId: '292212591013',
    projectId: 'project-1662196727563872745',
    authDomain: 'project-1662196727563872745.firebaseapp.com',
    storageBucket: 'project-1662196727563872745.appspot.com',
    measurementId: 'G-Y9Y1C6NEXR',
  );
}
